#! /bin/sh

# Autostart applications
## Resolution (xrandr, arandr, autorandr)
autorandr -c

## Compositor (Picom)
#picom -b

## Screenshot
flameshot &

## Network Manager Applet
nm-applet &

# Notification Daemon
dunst &

## Set Wallpaper (feh)
~/.fehbg &

## Status Bar (Polybar)
$HOME/.config/polybar/launch.sh &

# bspwm settings
xsetroot -cursor_name left_ptr
pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 &

bspc config border_width         2
bspc config window_gap           10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

## Pywal colors
# source the colors.
#. "${HOME}/.cache/wal/colors.sh"

# Set the border colors.
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color6"
# Use the line below if you are on bspwm >= 0.9.4
bspc config presel_feedback_color "$color1"
# Use the line below if you are on bspwm < 0.9.4
#bspc config presel_border_color "$color1"
